CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TYPE "booking_type" AS ENUM ('reservation', 'lesson', 'blocked', 'other');
CREATE TYPE "booking_status" AS ENUM ('active', 'cancelled');
CREATE TYPE "payment_status" AS ENUM ('pending', 'paid');

CREATE TABLE "clubs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "name" text NOT NULL, "slug" text NOT NULL UNIQUE, "access_code_hash" text NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "last_access_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "club_settings" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL UNIQUE REFERENCES "clubs"("id"), "slot_duration_minutes" integer NOT NULL DEFAULT 90, "payment_tracking_enabled" boolean NOT NULL DEFAULT false, "timezone" text NOT NULL DEFAULT 'Europe/Madrid', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "courts" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "name" text NOT NULL, "sort_order" integer NOT NULL DEFAULT 0, "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "business_hours" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "day_of_week" integer NOT NULL CHECK ("day_of_week" BETWEEN 0 AND 6), "opening_time" time, "closing_time" time, "is_closed" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), UNIQUE("club_id", "day_of_week"));
CREATE TABLE "special_hours" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "date" date NOT NULL, "opening_time" time, "closing_time" time, "is_closed" boolean NOT NULL DEFAULT false, "reason" text, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), UNIQUE("club_id", "date"));
CREATE TABLE "booking_recurrences" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "court_id" uuid NOT NULL REFERENCES "courts"("id"), "type" "booking_type" NOT NULL, "customer_name" text, "notes" text, "start_date" date NOT NULL, "end_date" date NOT NULL, "day_of_week" integer NOT NULL CHECK ("day_of_week" BETWEEN 0 AND 6), "start_time" time NOT NULL, "duration_slots" integer NOT NULL DEFAULT 1 CHECK ("duration_slots" > 0), "payment_status" "payment_status" NOT NULL DEFAULT 'pending', "is_active" boolean NOT NULL DEFAULT true, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "bookings" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "court_id" uuid NOT NULL REFERENCES "courts"("id"), "starts_at" timestamptz NOT NULL, "ends_at" timestamptz NOT NULL, "type" "booking_type" NOT NULL, "customer_name" text, "notes" text, "payment_status" "payment_status" NOT NULL DEFAULT 'pending', "status" "booking_status" NOT NULL DEFAULT 'active', "recurrence_id" uuid REFERENCES "booking_recurrences"("id"), "cancelled_at" timestamptz, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), CHECK ("ends_at" > "starts_at"));
CREATE INDEX "bookings_club_starts_idx" ON "bookings" ("club_id", "starts_at");
CREATE INDEX "bookings_court_starts_idx" ON "bookings" ("court_id", "starts_at");
ALTER TABLE "bookings" ADD CONSTRAINT "bookings_active_court_no_overlap" EXCLUDE USING gist ("court_id" WITH =, tstzrange("starts_at", "ends_at", '[)') WITH &&) WHERE ("status" = 'active');
CREATE TABLE "audit_logs" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "actor_type" text NOT NULL, "actor_id" text, "action" text NOT NULL, "entity_type" text NOT NULL, "entity_id" uuid, "previous_data" jsonb NOT NULL DEFAULT '{}'::jsonb, "new_data" jsonb NOT NULL DEFAULT '{}'::jsonb, "created_at" timestamptz NOT NULL DEFAULT now());
CREATE INDEX "audit_logs_club_created_idx" ON "audit_logs" ("club_id", "created_at");
CREATE TABLE "club_sessions" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "club_id" uuid NOT NULL REFERENCES "clubs"("id"), "token_hash" text NOT NULL UNIQUE, "expires_at" timestamptz NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "last_used_at" timestamptz NOT NULL DEFAULT now());
CREATE TABLE "superadmins" ("id" uuid PRIMARY KEY DEFAULT gen_random_uuid(), "email" text NOT NULL UNIQUE, "password_hash" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "last_login_at" timestamptz);
