"use client";

import { useState, useTransition } from "react";
import { Lock, Plus, UserRound } from "lucide-react";
import { cancelBooking, createBooking } from "@/app/actions";
import { localTime } from "@/lib/time";

type Data = { settings: { slotDurationMinutes: number; timezone: string }; courts: { id: string; name: string }[]; slots: string[]; bookings: { courtId: string; startsAt: Date; endsAt: Date; customerName: string | null; type: "reservation" | "lesson" | "blocked" | "other" }[] };
type Selected = { courtId: string; courtName: string; time: string };
const labels = { reservation: "Reserva", lesson: "Clase", blocked: "Bloqueo", other: "Otro" };
const styles = { reservation: "border-blue-200 bg-blue-50 text-blue-950", lesson: "border-amber-200 bg-amber-50 text-amber-950", blocked: "border-slate-300 bg-slate-100 text-slate-800", other: "border-violet-200 bg-violet-50 text-violet-950" };

export function AvailabilityBoard({ slug, date, data }: { slug: string; date: string; data: Data }) {
  const [onlyAvailable, setOnlyAvailable] = useState(false); const [selected, setSelected] = useState<Selected | null>(null); const [pending, startTransition] = useTransition(); const [message, setMessage] = useState<string | null>(null); const [createdId, setCreatedId] = useState<string | null>(null);
  const entry = (courtId: string, time: string) => data.bookings.find((booking) => booking.courtId === courtId && localTime(booking.startsAt, data.settings.timezone) <= time && localTime(booking.endsAt, data.settings.timezone) > time);
  const visible = onlyAvailable ? data.courts.filter((court) => data.slots.some((slot) => !entry(court.id, slot))) : data.courts;
  const firstOpen = data.courts.flatMap((court) => data.slots.filter((slot) => !entry(court.id, slot)).map((time) => ({ court, time }))).slice(0, 3);
  return <section>
    {message && <div role="status" className="mb-4 flex items-center justify-between gap-3 rounded-lg bg-emerald-50 p-3 font-medium text-emerald-900"><span>{message}</span>{createdId && <button onClick={() => startTransition(async () => { const result = await cancelBooking(createdId, slug); setMessage(result.success ?? result.error ?? null); setCreatedId(null); })} className="rounded-md px-2 py-1 text-sm font-bold underline">Deshacer</button>}</div>}
    <div className="mb-4 flex flex-wrap items-center gap-2"><div className="flex gap-2" role="group" aria-label="Filtro de disponibilidad"><button onClick={() => setOnlyAvailable(false)} className={`rounded-full px-4 py-2 text-sm font-semibold ${!onlyAvailable ? "bg-emerald-700 text-white" : "bg-white"}`}>Todas</button><button onClick={() => setOnlyAvailable(true)} className={`rounded-full px-4 py-2 text-sm font-semibold ${onlyAvailable ? "bg-emerald-700 text-white" : "bg-white"}`}>Con huecos</button></div><button onClick={() => { const first = firstOpen[0]; if (first) setSelected({ courtId: first.court.id, courtName: first.court.name, time: first.time }); }} className="ml-auto flex items-center gap-1 rounded-lg bg-emerald-700 px-3 py-2 text-sm font-bold text-white"><Plus size={17}/>Reserva</button></div>
    {visible.length === 0 ? <div className="rounded-xl bg-white p-8 text-center"><p className="font-bold">No hay pistas con huecos.</p><button onClick={() => setOnlyAvailable(false)} className="mt-2 font-semibold text-emerald-700">Ver todas las pistas</button></div> : <div className="space-y-4 md:hidden">{visible.map((court) => <div key={court.id} className="rounded-xl bg-white p-4 shadow-sm"><h2 className="mb-3 font-bold">{court.name}</h2><div className="grid grid-cols-2 gap-2">{data.slots.map((slot) => <Slot key={slot} time={slot} booking={entry(court.id, slot)} onSelect={() => setSelected({ courtId: court.id, courtName: court.name, time: slot })}/>)}</div></div>)}</div>}
    <div className="hidden overflow-x-auto rounded-xl bg-white shadow-sm md:block"><div className="grid min-w-[720px]" style={{ gridTemplateColumns: `90px repeat(${visible.length}, minmax(150px, 1fr))` }}><div className="border-b p-4 text-sm text-slate-500">Hora</div>{visible.map((court) => <div key={court.id} className="border-b border-l p-4 font-bold">{court.name}</div>)}{data.slots.map((slot) => <div key={slot} className="contents"><div className="border-b p-4 text-sm font-semibold">{slot}</div>{visible.map((court) => <div key={court.id} className="border-b border-l p-2"><Slot time={slot} booking={entry(court.id, slot)} onSelect={() => setSelected({ courtId: court.id, courtName: court.name, time: slot })}/></div>)}</div>)}</div></div>
    {selected && <div className="fixed inset-x-4 bottom-22 z-20 rounded-xl border border-emerald-200 bg-white p-4 shadow-xl md:inset-x-auto md:right-8 md:bottom-8 md:w-96"><h2 className="font-bold">Nueva reserva</h2><p className="mb-3 text-sm text-slate-600">{selected.courtName} · {selected.time}</p><form action={(formData) => startTransition(async () => { const result = await createBooking(formData); if (result?.success) { setMessage(result.success); setCreatedId(result.bookingId ?? null); setSelected(null); } else if (result?.error) setMessage(result.error); })} className="space-y-3"><input type="hidden" name="slug" value={slug}/><input type="hidden" name="date" value={date}/><input type="hidden" name="courtId" value={selected.courtId}/><input type="hidden" name="startTime" value={selected.time}/><label className="block text-sm font-medium">Tipo<select name="type" className="mt-1 w-full rounded-lg border p-2"><option value="reservation">Reserva</option><option value="lesson">Clase</option><option value="blocked">Bloqueo</option><option value="other">Otro</option></select></label><label className="block text-sm font-medium">Nombre<input name="customerName" className="mt-1 w-full rounded-lg border p-2" placeholder="Nombre de la reserva"/></label><label className="block text-sm font-medium">Duración<select name="durationSlots" className="mt-1 w-full rounded-lg border p-2"><option value="1">1 turno</option><option value="2">2 turnos</option><option value="3">3 turnos</option></select></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setSelected(null)} className="rounded-lg px-3 py-2">Cancelar</button><button disabled={pending} className="rounded-lg bg-emerald-700 px-3 py-2 font-semibold text-white">{pending ? "Reservando..." : "Guardar reserva"}</button></div></form></div>}
  </section>;
}
function Slot({ time, booking, onSelect }: { time: string; booking?: Data["bookings"][number]; onSelect: () => void }) { if (booking) return <div className={`flex min-h-16 items-center gap-2 rounded-lg border px-3 text-sm font-medium ${styles[booking.type]}`}>{booking.type === "blocked" ? <Lock size={16}/> : <UserRound size={16}/>}<span>{booking.customerName || labels[booking.type]}</span></div>; return <button onClick={onSelect} className="flex min-h-16 w-full flex-col items-center justify-center rounded-lg border border-dashed border-emerald-300 bg-emerald-50 text-sm font-semibold text-emerald-800 hover:bg-emerald-100"><span className="md:hidden">{time}</span><span className="flex items-center gap-1"><Plus size={16}/>Libre</span></button>; }
